### ISSUE TITLE
META: work plan for cureent issues

### ISSUE THREAD

**Issue by wmyrda** [essandess/adblock2privoxy#26]
Importance (low/medium/severe) and scope of required work (trivial/normal/high).

- [x] **adblock2privoxy compilation fail with GHC 8.4.3** https://github.com/essandess/adblock2privoxy/issues/25
_fix compilation_ 
Medium - A2P still can be used with GHC 8.0, but needs to be future proof, severity would increase as time passes and older GHC would be phased out from distros
Normal - [Proposed solution](https://github.com/gentoo-haskell/gentoo-haskell/issues/701#issuecomment-416027299) seems not to severe to achieve and there are many [examples](https://github.com/gentoo-haskell/gentoo-haskell/commits/master) titled `tweak for ghc-8.4 `

- [ ] **TODO: remove matched element conversion** https://github.com/essandess/adblock2privoxy/issues/24
_implement new feature_
Medium - Most elements are removed by created css files after conversion of `##` rules, but some sites require that browser completely does not know existence of certain elements therefore they need to be removed prior to being feed to the client
High - Design feature from ground up

- [x] **translated records get dot in front which has adverse effects** https://github.com/essandess/adblock2privoxy/issues/23
_use prepared patch to fix rules for privoxy_
Severe - Without this many false positive catches may happen
Trivial - patch is ready for implementation

- [x] **disregarding information following $** https://github.com/essandess/adblock2privoxy/issues/22
_implement new feature_
Severe - Adblock is designed to use filters on certain conditions such as `~third-party` to specify whether filter should be used on third-party or first domains. Current implementation uses that filter for all conditions
High - Requires writing similar converter as in case of `ab2p-popup-filter` or `ab2p-handle-as-image-s` but also for `script`, `stylesheet`, `subdocument` and others

- [x] **empty rules** https://github.com/essandess/adblock2privoxy/issues/21
_add exceptions for conversion of rules not leading to any host or particular pattern_
Low - workarounds are present
Normal -  Probably requires few regex additions to current converter implementation

- [x] **element hidding whitelists undesired behaviour** https://github.com/essandess/adblock2privoxy/issues/20
_redesign whitelist expception handling_
Low - workarounds are present & it could interfere with browsing only or rare 
Normal -  Probably requires few regex additions to current converter implementation

- [x] **easylist go.*. rule breaks many sites** https://github.com/essandess/adblock2privoxy/issues/19
_use prepared patch to fix rules for privoxy_
Severe - Without this many false positive catches may happen
Trivial - patch is ready for implementation

- [x] **adblock2privoxy segmentation fault** https://github.com/essandess/adblock2privoxy/issues/18
_make sure element hiding directory is empty before new rules are created_
Severe - typical race condition which in worst case scenario can lead to system crash
Trivial - if exists `rm -r ${css_dir}\*` before any `##` rules are created

- [x] **ab2p.common.css causes breakage on some sites** https://github.com/essandess/adblock2privoxy/issues/17
- separate ab2p-elemhide-common-filter from ab2p-elemhide-filter
- add all hosts from rules with $generichide to {-filter{ab2p-elemhide-common-filter}}

Medium - about 1% of all sites using element hiding rules may not use generic hide
Trivial/High - Above steps are trivial, but getting converter to process all $generichide rules an add them in right way required coding new feature from ground up

- [x] **version string of filter is truncated if it not composed only of digits** https://github.com/essandess/adblock2privoxy/issues/16
_cosmetic change to the task file_
Low - does not change any behavior of converter, just descriptive value
Trivial - small change required 

- [x] **expired rules are not used** https://github.com/essandess/adblock2privoxy/issues/15
_implement way for a2p to use other filtersets than only those designed for adblock (eg. adguard)_
Low - without this quite number of rules are skipped, but workaround is present
Normal - several conditions may have to be added for accepting list other than those for adblock

- [x] **conversion errors - not abp specific** https://github.com/essandess/adblock2privoxy/issues/14
_related to bug 22 as it requires additional convertions currently not implemented_
- /#
- #?#
- Low - cases are rare and in case of #?# undocumented, but they [happen](https://github.com/easylist/easylist/issues/1575)
Normal - Few changes in regex may be needed to address this issue

- [x] **unblock rules too unspecific for certain sites** https://github.com/essandess/adblock2privoxy/issues/13
_duplicate of issue 17, but better describes problem_

- [ ] **add support pre-processor directives for filters** https://github.com/essandess/adblock2privoxy/issues/12
_use only filters which will be understood_
Medium - cases where several approaches are taken for specific software to handle given problem are out there and specially present in lists designed for adguard
High - Implement feature from ground up

- [x] **css file could use new line for site specific rules** https://github.com/essandess/adblock2privoxy/issues/11
_implement proper :style() conversion for css files_
- High - Over 10 thousands rules
Trivial/High - trivial if only `Elements=4000` is changed to `Elements=1`, but may be high as would require change to way in which css files are created

- [x] **Double rules on filters are too broad** https://github.com/essandess/adblock2privoxy/issues/10
_limit converter to generate only one rule line per record_
Medium - I would say high as it leads to creating too many broad rules, but workarounds are present
Normal - probably requires fixes here and there

- [x] **privoxy crash due to bad filter combination** https://github.com/essandess/adblock2privoxy/issues/7
_simple template change, fix ready_
Severe - without fix privoxy crashes
Trivial - patch is ready

- [x] **adblock2privoxy errors out on several records** https://github.com/essandess/adblock2privoxy/issues/6
_implementing new conversion methods where privoxy needs to inject javascript_
High - affects hundreds of pages which require parts of scripts to be blocked prior to being used by the browser
High - Design feature from ground up

**Comment by essandess** [comment]
@wmyrda thanks again for compiling this helpful list. All items that can be addressed now have been, so I’m closing this and we can discuss individual issues per item.
